-- NXS Streamers - minimal Supabase schema used directly by the extension
-- Run this in the Supabase SQL Editor of your own project.
--
-- Important:
-- 1. This matches the current client-side implementation.
-- 2. The extension writes to these tables directly from the browser.
-- 3. That requires permissive anon policies below.
-- 4. For production hardening, move these writes behind your backend or Edge Functions.

create table if not exists public.backend_config (
  id bigint generated by default as identity primary key,
  current_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.otp_requests (
  id bigint generated by default as identity primary key,
  discord_id text not null,
  code text not null,
  used boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_otp_requests_discord_created
  on public.otp_requests (discord_id, created_at desc);

alter table public.backend_config enable row level security;
alter table public.otp_requests enable row level security;

drop policy if exists public_backend_config_access on public.backend_config;
create policy public_backend_config_access
  on public.backend_config
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists public_otp_requests_access on public.otp_requests;
create policy public_otp_requests_access
  on public.otp_requests
  for all
  to anon
  using (true)
  with check (true);

insert into public.backend_config (id, current_url)
values (1, 'https://your-backend.example.com')
on conflict (id) do update
set current_url = excluded.current_url;
